Add shadow spray action
ShutdownRepo/pywhisker pull request #6
Opened 2022-10-11 23:24 UTC by snovvcrash

Hey @ShutdownRepo, @p0dalirius!

I was already going to sleep when decided to swipe Twitter's feed a bit and... I couldn't deny myself this PR after reading about [ShadowSpray](https://github.com/Dec0ne/ShadowSpray).

It's very quick and dirty and all it implements is a `for` loop and lack of info messages but I guess it could be helpful anyways c:

![demo](https://user-images.githubusercontent.com/23141800/195215992-1ba1e9a4-f715-4d0c-aafa-b775a5e9e271.png)

2022-10-12 16:34 UTC, ShutdownRepo requested changes
Awesome addition! I have some change request though, in my opinion the `for` loop should take place after the KCL blob is created. That way, all users will be sprayed with the exact same key pair and the user won't have to keep track of what key belongs to what victim.
Also, line 417 could be changed to something like
```python
logger.success(f"Updated the msDS-KeyCredentialLink attribute of the target objects: {",".join(targets)}")
```
What do you think?

2022-10-12 18:13 UTC, snovvcrash commented
That's a good point!

I've fixed that the following way: in the beginning of the spray we create a single certificate with a randomly chosen target from the list to be the owner of the certificate (its `samname` and `dn` are populated within the `subject` and `owner` properties of the certificate respectively).

Regarding the changes for line 417 - I still think we should keep pywhisker printing successful attempts line by line 'cause it's more like the spraying style I guess (like we're used to see it with kerbrute, for example). Moreover, in large environments it may take time for the spray to complete and we shall not see the results until it finishes. Here's how it looks like line by line ⏬ 

![demo](https://user-images.githubusercontent.com/23141800/195416839-8fd59b12-76a4-4109-bad5-c4c5f86c44a2.png)

But it's up to you to decide!

2022-10-13 10:45 UTC, ShutdownRepo commented
Agreed 100%, merging, thank you @snovvcrash !

2022-10-13 10:45 UTC, ShutdownRepo approved these changes

2022-10-13 10:45 UTC, merged